pipeline{
    parameters{
        choice(name: 'terraformAction', choices: ['Apply', 'Destroy'], description: 'Choose terraform action to perform')
    }
environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
    }
    agent any
    stages{
        stage ('Git Checkout') {
            steps{
                script {
                    dir("Terraform") {
                        git url :'https://github.com/Nikhil-Raghav/EKS_Cluster_CICD.git', branch:'main'
                    }
                }
            }
        }
        stage ('Planning') {
            steps{
               
                    sh 'pwd; cd eks/; terraform init'
                    sh 'pwd; cd eks/; terraform plan -out tfplan'
                    sh 'pwd; cd eks/; terraform show -no-color tfplan > tfplan.txt'

            }
        }
        stage('Approval'){
            steps{
                script{
                    def plan = readFile 'eks/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy'){
            when {
                expression{
                    return  params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                } 
            }
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                        sh 'pwd; cd eks/; terraform apply -input=false tfplan'
                    }
                    else if (params.terraformAction == 'destroy'){
                        sh 'pwd; cd eks/; terraform destroy -auto-approve'
                    }
                }
            }
        }

        stage('Backup-Stage'){
            steps{
                sh '''
                    pwd 
                    cd eks/
                    aws s3 cp terraform.tfstate s3://itkannadogaru-terraform-tf-backup/Chat-bot/dev-eks/
                '''
            }
        }
    }

}
