pipeline{
    parameters{
        choice(name: 'terraformAction', choices: ['Apply', 'Destroy'], description: 'Choose terraform action to perform')
    }
environment {
        AWS_ACCESS_KEY_ID = credentials.('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials.('aws-secret-access-key')
    }
    agent any
    stages{
        stage ('Git Checkout') {
            steps{
                script {
                    dir("Terraform") {
                        git url :'https://github.com/Nikhil-Raghav/EKS_Cluster_CICD.git', branch:'main'
                    }
                }
            }
        }
        stage ('Planning') {
            steps{
               
                    sh 'pwd; cd eks/; terraform init'
                    sh 'pwd; cd eks/; terraform plan -out tfplan'
                    sh 'pwd; cd eks/; terraform show -no-color tfplan > tfplan.txt'

            }
        }
        stage ('Approval') {
            steps{
                script{
                    def plan = readFile 'eks/tfplan.txt'
                    input message: "Do you want to proceed with terraform actions..?"
                }
            }

        }
    }

}